frr version 10.7
frr defaults traditional
hostname core1
log stdout informational
service integrated-vtysh-config
!
interface eth2
 ip ospf network point-to-point
!
router ospf
 ospf router-id 10.255.255.1
 passive-interface default
 no passive-interface eth2
 network 10.10.10.0/24 area 0.0.0.0
 network 10.10.20.0/24 area 0.0.0.0
 network 10.10.30.0/24 area 0.0.0.0
 network 10.10.40.0/24 area 0.0.0.0
 network 10.255.0.0/30 area 0.0.0.0
 network 10.255.255.1/32 area 0.0.0.0
 log-adjacency-changes
!
line vty
!
