frr version 10.7
frr defaults traditional
hostname edge-fw1
log stdout informational
service integrated-vtysh-config
!
interface eth1
 ip ospf network point-to-point
!
router ospf
 ospf router-id 10.255.255.2
 passive-interface default
 no passive-interface eth1
 network 10.255.0.0/30 area 0.0.0.0
 network 10.255.255.2/32 area 0.0.0.0
 log-adjacency-changes
!
line vty
!
