frr version 10.7
frr defaults traditional
hostname edge-fw1
log stdout informational
service integrated-vtysh-config
!
interface eth1
 ip ospf network point-to-point
!
ip prefix-list AWS-VPC seq 5 permit 10.50.0.0/16
!
route-map AWS-VPC-ONLY permit 10
 match ip address prefix-list AWS-VPC
!
ip route 10.50.0.0/16 wg0
!
router ospf
 ospf router-id 10.255.255.2
 passive-interface default
 no passive-interface eth1
 network 10.255.0.0/30 area 0.0.0.0
 network 10.255.255.2/32 area 0.0.0.0
 redistribute static route-map AWS-VPC-ONLY
 log-adjacency-changes
!
line vty
!
